version: '3.9'
services:
  app:
    build: .
    container_name: stocks-dashboard
    ports:
      - "8080:8080"
    environment:
      - APP_PORT=8080
      - CSV_ROOT=/data
      - EXPORT_DIR=/app/exports
      - PDF_TITLE=Stocks Dashboard
    volumes:
      - ./:/data
      - ./exports:/app/exports
    restart: unless-stopped

